# Copy this file name as secrets.yml in config folder and setup your username password and database name
development:
    username: 'YOUR_MYSQL_USERNAME'
    password: 'YOUR_MYSQL_PASSWORD'
    database: 'DATABASE_NAME'